{% set name = "padelpy" %}
{% set version = "0.1.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/padelpy-{{ version }}.tar.gz
  sha256: bbe11fd93b3f7914f57b5dafbf83c5070161246fce4c626c1f394d73efabf394

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - openjdk

test:
  imports:
    - padelpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ecrl/padelpy
  summary: A Python wrapper for PaDEL-Descriptor
  license: AGPL-3.0-only AND LGPL-2.1-only AND MIT
  license_file:
    - padelpy/PaDEL-Descriptor/license/LICENSE.txt
    - padelpy/PaDEL-Descriptor/license/lgpl-2.1.txt
    - padelpy/PaDEL-Descriptor/license/lgpl.license
    - LICENSE
extra:
  recipe-maintainers:
    - maclandrol
